on: workflow_dispatch
name: ExportChannelTest
jobs:
  build:
    name: ExportChannelTest
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        AWS_KEY: ${{ secrets.IMG_AWS_KEY }}
        AWS_SECRET: ${{ secrets.IMG_AWS_SECRET }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script_stop: true
        envs: AWS_KEY, AWS_SECRET
        script: |
          docker version
          docker run --rm -v /opt/STORAGE/exported_channels:/out tyrrrz/discordchatexporter:stable export -t BOT_KEY=$DISCORD_BOT_KEY -c 1142100229072638023
